### PR TITLE
#159461602 Change User Roles 

### PR DESCRIPTION
**Pull request by Bonifase**
#### What does this PR do?
 Allow users to have an end point from which the admin can change user roles,
 such as `Default User` to `Admin` and `Admin` to `Default User`
#### How should this be manually tested?
- Run the server
- Test the queries at localhost:5000/mrm
- Run `changeUserRole` mutation with `email` and `roleId` as  the keyword arguments
#### Screenshots 
     When a user performing the action is not an admin.
screen shot 2018-08-13 at 21 20 09
     When a user whose role is being changed is not available.
screen shot 2018-08-13 at 21 26 39
     When the correct user is found.
screen shot 2018-08-13 at 21 31 40

#### What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/159461602

### CODE REVIEW

**Comment by kevinbett** [comment]
Check your git commit message and omit the `II# interactive rebase in progress; onto 5c304d5` reference that seems to have snuck in.

**Comment by Bonifase** [comment]
`check_office_name.py` was as a result of the rebase I did on the HEAD, otherwise, it is now fixed @mutoromike and @peterwade153

**Comment by kevinbett** [comment]
LGTM.

**Comment by shemogumbe** [comment]
You might need to resolve the merge conflicts on this branch before merge.

**Pull request merged**
