### PR TITLE
 #159357284 Fix codeclimate Issues on backend

### PR DESCRIPTION
**Pull request by peterwade153**
What does this PR do?
Fix codeclimate Issues on backend

What are the relevant Pivotal Tracker stories?
ID: #159357284
Story: Fix codeclimate Issues on backend

### CODE REVIEW

**Comment by mutoromike** [comment]
Good work fixing the tests!

**Comment by mutoromike** [comment]
Also, remember to work on the Codeclimate file before this can be merged.

**Comment by kevinbett** [comment]
I have also tagged the file we have ignored and given a reason on code-climate

**Comment by peterwade153** [comment]
We worked on that

**Comment by peterwade153** [comment]
@mutoromike Change has been effected

**Comment by mutoromike** [comment]
LGTM now...

**Pull request merged**
