### PR TITLE
CON-272  Capture recurring events in analytics data

### PR DESCRIPTION
**Pull request by rajeman**
## Description ##
 Currently, analytics for recurring events are not properly captured as these events are stored in our `DB` as `a single instance of several events`. This precludes the `allAnalytics` and related queries from capturing the recurring/other-instances of such events. This PR ensures recurring events are stored as separate events (with a common `recurring_event_id`) and thus automatically captured by all analytics related queries.

**How should this be manually tested?**
  - You can book any of the available test rooms for a recurring event
  - Sync your `DB` and all instances of the recurring event are saved. 
  - Note that recurring events are capped at 730 instances by the Google Calendar API

## Type of change ##
Please select the relevant option
- [x] Bug fix(a non-breaking change which fixes an issue)
- [ ] New feature(a non-breaking change which adds functionality)
- [ ] Breaking change(fix of a feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ##
- [x] My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes

### JIRA
[CON-272](https://andela-apprenticeship.atlassian.net/browse/CON-272)

### CODE REVIEW

**Comment by joshuaocero** [comment]
@rajeman what happens to recurring events that are currently stored in the DB as one recurring event? Will the next sync spread them out or will this fix only work for future events?

**Comment by rajeman** [comment]
@joshuaocero No. They won't be spread out.  This fix works for only future events.

**Comment by rajeman** [comment]
@joshuaocero We cater for previous events by making a full sync.

**Comment by rajeman** [comment]
@mnswaleh Full sync will allow recurring events that have already been stored as a single instance to be stored as separate events.

**Pull request merged**
