### PR TITLE
CON-307 Setup subscriptions server

### PR DESCRIPTION
**Pull request by IssaIan**
#### Description
Setup the app subscription server on which all subscription-related implementation will be built on. 

#### How this should be manually tested
Clone the repo: git clone https://github.com/andela/mrm_api.git.
Setup the project as per the README.md.
Checkout to branch story/CON-307-setup-subscription-server.
Ensure to `pip install -r requirements.txt`.
Server should run normally.
#### Type of change
- [ ] Bug fix (nonbreaking change which fixes an issue)
- [x] New feature (nonbreaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### How Has This Been Tested?
Please describe the tests that you ran to verify your changes
- [ ] End to end
- [ ] Integration

#### Checklist:
- [x] My code follows the style guide for this project
- [x] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

#### Jira
[CON-307](https://andela-apprenticeship.atlassian.net/browse/CON-307)

### CODE REVIEW

**Comment by joshuaocero** [comment]
@IssaIan the last I heard about this, we were having a separate container for the subscriptions server. This PR does not seem to be archiving that. Please shed some light on this.

**Comment by IssaIan** [comment]
> @IssaIan the last I heard about this, we were having a separate container for the subscriptions server. This PR does not seem to be archiving that. Please shed some light on this.

@joshuaocero as I texted you earlier in the morning, we figured a way out with Emmanuel Raji to implement the sockets within the mrm_api application. @rajeman figured out what we were doing wrong within the deployment scripts.

**Comment by IssaIan** [comment]
> > @IssaIan the last I heard about this, we were having a separate container for the subscriptions server. This PR does not seem to be archiving that. Please shed some light on this.
> 
> @joshuaocero as I texted you earlier in the morning, we figured a way out with Emmanuel Raji to implement the sockets within the mrm_api application. @rajeman figured out what we were doing wrong within the deployment scripts.

We shall be migrating to separate containers later. This is a temporary implementation before we figure out a way forward.

**Comment by IssaIan** [comment]
> > @IssaIan the last I heard about this, we were having a separate container for the subscriptions server. This PR does not seem to be archiving that. Please shed some light on this.
> 
> @joshuaocero as I texted you earlier in the morning, we figured a way out with Emmanuel Raji to implement the sockets within the mrm_api application. @rajeman figured out what we were doing wrong within the deployment scripts.

This is a temporary implementation. We are going to migrate to separate containers in a later implementation.

**Pull request closed without merging**
