### PR TITLE
 #165848937 Remove redundant code from the old structure model

### PR DESCRIPTION
**Pull request by Arusey**
**What does this PR do?**
- Removes the old structure model from the codebase
- Refactors some of the fixtures and tests from the codebase

**Description of the task to be completed?**
- Clean up the codebase by removing the redundant code

**How should this be manually tested?**
- Update your dump data to the latest
- After checking into the branch 
- Run `make ssh service=app`
- run `export $(cat .env | xargs)`
- Finally, run `alembic upgrade head`
`

**What are the relevant pivotal tracker stories?**
[#165848937](https://www.pivotaltracker.com/n/projects/2154921/stories/165848937)

**Checklist**
- [x]  My code follows the style guidelines of this project
- [x] I have linted my code prior to submission
- [x] I have made the corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Implementation works according to expectations

### CODE REVIEW

**Comment by Arusey** [comment]
> @Arusey kindly squash your commit into one to help keep the history clean. Good Job

Noted

**Comment by Arusey** [comment]
> @Arusey kindly squash your commit into one to help keep the history clean. Good Job

Done

**Comment by Arusey** [comment]
> Hey, your implementation only works with an empty database, the migrations don't run with a pre-populated database. I get this error `constraint locations_structure_id_fkey on table locations depends on table structure`. Kindly look into this.

Hello, when running migrations you have to reorganize the alembic file commands to be synonymous with what I have uploaded after autogenerate.

**Comment by rajeman** [comment]
@Arusey Can you kindly explain how the migration will work with a pre-populated database using docker? I am experiencing the same issue with @kwanj-k

**Comment by Arusey** [comment]
> ~Looks good to me.~
> It works on a clean database but not on one with populated data. Attached is a screenshot for context
> Screenshot 2019-05-15 at 12 31 23 PM

Run initial migrations `make migrate-initial message="Migration message"`

**Comment by Arusey** [comment]
> @Arusey Can you kindly explain how the migration will work with a pre-populated database using docker? I am experiencing the same issue with @kwanj-k

Run initial migrations in the event of prepopulated data

**Comment by Bonifase** [comment]
> > @Arusey Can you kindly explain how the migration will work with a pre-populated database using docker? I am experiencing the same issue with @kwanj-k
> 
> Run initial migrations in the event of prepopulated data

Why do we need to run initial migration yet I already have all the tables? I think we should only migrate the affected table(s)

**Comment by Arusey** [comment]
> > > @Arusey Can you kindly explain how the migration will work with a pre-populated database using docker? I am experiencing the same issue with @kwanj-k
> > 
> > 
> > Run initial migrations in the event of prepopulated data
> 
> Why do we need to run initial migration yet I already have all the tables? I think we should only migrate the affected table(s)

I think there was a problem with my postgres version it did not drop the table as required. I will update the PR as required.

**Comment by Arusey** [comment]
> Kindly check on your commit messages. You should have only one atomic commit message.

Done

**Comment by Arusey** [comment]
> I can see you have made changes in the analytics files. How does this task affect these files?

I did not make any changes I think this happened during the rebase. But lemme look through them to make sure I did not remove anything.

**Pull request merged**
