### PR TITLE
Clean develop branch

### PR DESCRIPTION
**Pull request by PatrickCmd**
#### What does this PR do?
- Clean develop by removing unnecessary __pycache__ directories

#### Description of Task to be completed?
- N/A

#### How should this be manually tested?
- N/A

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- N/A

### CODE REVIEW

**Comment by owenbob** [comment]
Changes required in `alembic/env.py`. There were double imports for the `os` and `sys`

**Comment by owenbob** [comment]
This code ```sys.path.append(os.getcwd())
config.set_main_option('sqlalchemy.url', os.getenv('DEV_DATABASE_URL'))``` is still duplicated in the `alembic/env.py`

**Comment by PatrickCmd** [comment]
@owenbob  alembic/env.py has been modified.

**Comment by JoyLubega** [comment]
@PatrickCmd  what about the folder Resource and room_resource?? I got issues with it yesterday

**Comment by JoyLubega** [comment]
LGTM!

**Pull request merged**
